### PR TITLE
wip - Get Travis working

### PR DESCRIPTION
**Pull request by calebthompson**

### CODE REVIEW

**Comment by calebthompson** [comment]
Don't merge me!

**Comment by julianguyen** [comment]
@calebthompson 💯  yess thank you so much for tackling this! I tried to setup Travis, but I have no idea how to >.<

**Comment by julianguyen** [comment]
@calebthompson Hey any updates? :)

**Comment by starbelly** [comment]
@julianguyen Looks like you may still need help getting travis setup... If so and @calebthompson is too busy, I'll jump on this before the panic button issue.

**Comment by calebthompson** [comment]
I got pulled onto a project so my availability to finish this is limited. It'll be at least a couple of weeks until I can focus on it again, but I'm happy to do so at that point.

**Comment by julianguyen** [comment]
@starbelly Hey would you like to this on then?

**Comment by starbelly** [comment]
@julianguyen Yup, coming at ya soon.

**Pull request closed without merging**
