### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by HashNotAdam**
Includes changes related to:

- installing PostgreSQL on Linux;
- general rbenv information; and
- miscellaneous clarifications

Many of the commits have descriptions explaining their reasoning.

### CODE REVIEW

**Comment by andy5995** [comment]
Anyone have thoughts about adding a link to [_Development setup for Debian_](https://github.com/julianguyen/ifme/wiki/Development-setup-for-Debian) somewhere in the README?

**Comment by HashNotAdam** [comment]
How do you feel it would differ from what is in this PR?
I know the PostgreSQL install is a little different, which was the primary reason to suggest these changes—what else did you encounter?

**Comment by andy5995** [comment]
I don't really see any problems, just wanted to provide a friendly suggestion that both pages be reviewed for any changes because they're both related to setup and installation.

**Comment by HashNotAdam** [comment]
Sorry, master had changed so had to rebase

**Comment by HashNotAdam** [comment]
Thanks, guys!

**Pull request merged**
