### PR TITLE
Add error pages

### PR DESCRIPTION
**Pull request by georgetoothman**
we extracted the footer into a partial that is sticky -- the css on the home page is more responsive
@kegreen22
@ngewirtz
@iuliiakot

during hacker hours @thoughtbot

### CODE REVIEW

**Comment by julianguyen** [comment]
@georgetoothman How did you test how this works? I tried running localhost:3000/blah and I get a routing error instead of an error page

**Comment by georgetoothman** [comment]
hmm - http://localhost:3000/asdf should look like this screen shot 2015-11-16 at 9 40 39 am

**Comment by julianguyen** [comment]
@georgetoothman 
@kegreen22
@ngewirtz
@iuliiakot

Noticed in chrome that the sticky footer is broken
screen shot 2015-11-16 at 7 51 10 am

**Comment by georgetoothman** [comment]
yes, @julianguyen the sticky footer will climb up with the browser size covering the body. we were unable to resolve that within the working hours yesterday. a couple options we have now would be to set a maximum width for the body section, or add margin-top to the footer....

**Comment by julianguyen** [comment]
@georgetoothman Is that something you and others want to work on?

**Comment by georgetoothman** [comment]
Yep! Sounds like @iuliiakot has resolved these issues and will push to the
add-error-fix branch. Hopefully this can get incorporated today!!

**Comment by georgetoothman** [comment]
@julianguyen here is the latest working branch from @iuliiakot https://github.com/julianguyen/ifme/compare/master...IuliiaKot:master

**Comment by julianguyen** [comment]
@georgetoothman @iuliiakot Sounds great! Thanks for the update. We have a slack page if you want to continue have any discussions there. Just email join.ifme@gmail.com your email address and I'll send you an invite.

**Comment by julianguyen** [comment]
@georgetoothman @iuliiakot is your working branch ready to merge?

**Comment by IuliiaKot** [comment]
Hi,
Yes, for error page 404 it's ready to merge. I am on vacation right now,
but after I would like to finish for other errors.

**Comment by georgetoothman** [comment]
Just checking in on this- hope that branch makes it live!

**Comment by IuliiaKot** [comment]
Hi, sorry for the delay. It looks good. I think we can push our solution.

**Comment by julianguyen** [comment]
@IuliiaKot @georgetoothman Thanks for all the fabulous work! Can you make a pull request? :)

**Comment by georgetoothman** [comment]
For sure I will on Monday if Julia has not already. Can't wait to
contribute more for this project

**Pull request merged**
