### PR TITLE
CHANGELOG.txt: file added, one change documented

### PR DESCRIPTION
**Pull request by andy5995**

### CODE REVIEW

**Comment by andy5995** [comment]
I wanted to suggest adding this file. I think it could help give users and developers a concise way of seeing recent significant changes, and helps to show how the project is being actively developed.

**Comment by julianguyen** [comment]
Ooh this is a great idea, anyone else wanna chime in too?

**Comment by andy5995** [comment]
.md or .txt?

**Comment by julianguyen** [comment]
Markdown would be more readable to folks, good call!

**Comment by andy5995** [comment]
Closing w/o merge. Ticket opened #651

**Pull request closed without merging**
