### PR TITLE
Word wrap not working in comments - fixed issue

### PR DESCRIPTION
**Pull request by dominicprescod**
Fixed the issue of word wrap with css 

div.table div.table_cell {
    display: table-cell;
    word-break: break-word;
}

### CODE REVIEW

**Comment by julianguyen** [comment]
Thanks so much @dominicprescod! :)

**Comment by dominicprescod** [comment]
no problem! 
I changed the styling to the comments as well. 
screen shot 2016-04-30 at 1 33 47 pm

**Comment by julianguyen** [comment]
@dominicprescod can you resolve merge conflcits and then update this pull request? :)

**Comment by dominicprescod** [comment]
just fixed it...shouldn't have an issue now :-)

**Comment by julianguyen** [comment]
Great looks good to me!

**Pull request merged**
