### PR TITLE
Enhancement/Rubocop Offences

### PR DESCRIPTION
**Pull request by brunoocasali**

### CODE REVIEW

**Comment by julianguyen** [comment]
Hey @brunoocasali, can you condense some of the commits (so that it's easier to look through)?

**Comment by julianguyen** [comment]
@brunoocasali Does this https://github.com/julianguyen/ifme/pull/339 need to merge before this PR? Also please rebase this PR.

**Comment by brunoocasali** [comment]
@julianguyen I'm working on this pr yet! please don't merge it :+1:

**Comment by julianguyen** [comment]
How is this going?

**Pull request closed without merging**
