### PR TITLE
Issue #375: Add dropshadow on modal titlebar

### PR DESCRIPTION
**Pull request by su6a12**

### CODE REVIEW

**Comment by julianguyen** [comment]
Any updates on this @su6a12?

**Comment by su6a12** [comment]
Hey Julia,

I started working on it a few weeks ago, but couldn’t get my test environment up. I’ll try again this weekend if that’s ok. I’m pretty sure the fix I’ve got is good, just need to test it out to make sure.

Mel

**Comment by julianguyen** [comment]
Sounds good, thanks for the update! Feel free to ask any questions on Slack too ^^

**Comment by su6a12** [comment]
Hi Julia. Let me know if the updates I made are what's expected.

**Pull request merged**
