### PR TITLE
"#180 | Nicolette | Add Jasmine-Jquery Library"

### PR DESCRIPTION
**Pull request by nchambe2**
Add Jasmine Jquery Library

### CODE REVIEW

**Comment by julianguyen** [comment]
Is it better to import the library manually or use a gem?

**Comment by nchambe2** [comment]
It would be better to use the gem. I will push up the change.

**Comment by julianguyen** [comment]
Sounds good thanks @nchambe2! :D

**Comment by julianguyen** [comment]
I'm going to merge this actually - doesn't look like there's an official gem or one that has been updated recently.

**Pull request merged**
