### PR TITLE
Updated README: Link to a postgres tutorial for OSX

### PR DESCRIPTION
**Pull request by nagmak**
Added a link to the postgres tutorial I used. Let me know if I'm doing this right =D I've never created a pull request before

### CODE REVIEW

**Comment by starbelly** [comment]
@nagmak Definitely doing it right : ) Though, it looks like you are are a collaborator, so I don't think you needed to do the PR, unless you wanted to open a discussion on the link you're providing. I do think that this documentation is concise enough to where it makes more sense to add this to the README itself or perhaps in a separate INSTALL.md file.

**Comment by nagmak** [comment]
Yay :) As a collaborator I can make commits directly to the repo? So PR would be for more major changes or bugs then. Thanks for the feedback on that!

**Comment by starbelly** [comment]
@julianguyen Might be a good idea to establish guidelines for collaborators at this point. Do we do a PR for everything? Obviously this is somewhat of a negligible change, but maybe it shouldn't have just gone through. I assumed it would be fine since there were no rules or guidelines on the matter in place, in addition to the fact that @nagmak is a collaborator. Yet, still we need to be clear about all this, otherwise we could end up with a bit of a mess at some point.

**Comment by maestromusica** [comment]
I think that pull requests should be done for every change in the code. Just to make sure that 'another pair of eyes' will go through the changes to make sure no unwanted/dangerous side effects will be introduced to the codebase.

**Comment by julianguyen** [comment]
Agree with you two, please make PRs, you can push directly if you are undoing something. Sorry I did not make that clear. I will update the docs to clarify that!

**Pull request merged**
