### PR TITLE
added "translators" to contributors page

### PR DESCRIPTION
**Pull request by andy5995**

### CODE REVIEW

**Comment by andy5995** [comment]
I'd be totally willing to wait and re-submit this PR after #585 is merged. @alexiamcdonald let me know if there's anything I can do to keep things going smoothly.

**Comment by julianguyen** [comment]
Yeah let's merge @alexiamcdonald's epic Swedish translations first then you can update this PR once you rebase from master! Looking rad though! Thanks for this suggestion. We want to be as welcoming and inclusive as possible to potential contributors <3

**Comment by andy5995** [comment]
@julianguyen @alexiamcdonald I submitted a PR to #585 (to alexia's branch) that would include all the changes in this PR, but also includes the Swedish translation.

If alexia decides to merge it, then this PR can be closed.

**Comment by andy5995** [comment]
Thanks!

**Pull request merged**
