### PR TITLE
deleted 3 pending tests

### PR DESCRIPTION
**Pull request by Dawa12**
paired with @dleve123 on this, but we ran the app and found three pending tests. Upon closer examination we discovered they were auto generated and not in use. 

We also removed spec/views folder since two of the deleted pending tests were within it, and the folder was empty once we deleted those two pending tests. 

cc / @julianguyen

### CODE REVIEW

**Comment by julianguyen** [comment]
@Dawa12 @dleve123 Awesome clean up! Thanks so much :)

**Comment by dleve123** [comment]
@julianguyen: thanks!
@Dawa12: congratz!

**Comment by Dawa12** [comment]
Thanks @julianguyen for the chance to work on ifme. This was my first open source contribution. Thanks again @dleve123 for your guidance today.

**Comment by julianguyen** [comment]
That's amazing @Dawa12! Great job :) if you want to continue to contributing let me know!

**Comment by Dawa12** [comment]
Yes I'm interested! I'd like to make some contribution every week. I just
sent you an email

**Pull request merged**
