### PR TITLE
Freeze string literals

### PR DESCRIPTION
**Pull request by HashNotAdam**
Freezing string literals reduces the memory usage of the application. On the other hand, it means that you can not mutate strings and, as such, any existing code that does this needs to be modified.

### CODE REVIEW

**Comment by julianguyen** [comment]
What's the status on this? :)

**Comment by HashNotAdam** [comment]
@julianguyen it needs to be rebased so I was hoping to sort out the RGSoC PRs first, rebase this, and then I could help the RG pull those changes. I'll reevaluate that idea after speaking to them today. 😄

**Comment by HashNotAdam** [comment]
Hey, @julianguyen, this is now ready to merge.
Could you please approve again for me?

**Comment by julianguyen** [comment]
Done!

**Pull request merged**
