### PR TITLE
Added URL shortcuts for language settings

### PR DESCRIPTION
**Pull request by jsrn**
I put this together after reading #738 

I'm not sold on the technique, as you'd have to worry about keeping the list of localisations in the routes in sync with the list of available localisations.

Perhaps someone has an idea of how to handle it better?

:v:

### CODE REVIEW

**Comment by jsrn** [comment]
Great. :) Do you want me to do that now, or post-merge?

**Comment by sexybiggetje** [comment]
Merge it, then add it to the wiki. But won't matter much if you do it in the same timespan ;).

**Comment by jsrn** [comment]
I don't think I have the access rights to merge! But I'll keep an eye on my notifications and update the wiki when my PR is accepted.

Thanks for the review. :)

**Comment by sexybiggetje** [comment]
Oh I just assumed you did, merged it for you. Go ahead ^.^;
Thanks for the change.

**Comment by julianguyen** [comment]
@jsrn Can you add a follow-up PR for writing tests for this functionality? Great work!
cc: @sexybiggetje

**Comment by jsrn** [comment]
Sure! I'll try to do something in the next few days.

**Pull request merged**
