### PR TITLE
Piecedigital

### PR DESCRIPTION
**Pull request by piecedigital**

### CODE REVIEW

**Comment by aayushpi** [comment]
👍 LGTM, perhaps nit add .DS_Store to the gitignore so we can keep the commits cleaner.

**Comment by piecedigital** [comment]
I didn't change much in the `.gitignore`. I only added one thing there. See, I needed to change the `database.yml` file a little bit in order for the app to work for me. I didn't want that change to be included so I added the file to be ignored.

Still good?

**Comment by aayushpi** [comment]
Yep! Also, will be great if you add a description for future PRs, took me a little while to understand all the things you’re doing in there ~

**Comment by piecedigital** [comment]
Okay, great.

So I can just merge it myself?

**Comment by piecedigital** [comment]
Should I merge this myself? I just wanna be sure.

**Pull request merged**
